# import json
# import os
# import argparse
# from pathlib import Path

# #python /home/hnz/BRCD-main/create_txt_files.py --gnd gnd.json --originals_dir jpg --attack_dir attack_images --target_dir .

# def main():
#     parser = argparse.ArgumentParser(description="Generate train.txt, test.txt, and database.txt from gnd.json.")
    
#     # --- 必需的参数 ---
#     parser.add_argument(
#         "--gnd", 
#         required=True, 
#         help="Path to the 'gnd_SCID.json' file generated by image_attack.py."
#     )
    
#     parser.add_argument(
#         "--originals_dir", 
#         required=True,
#         help="The relative path to the directory where your 40 *original* query images are stored (e.g., 'data/SCID/originals')."
#     )

#     parser.add_argument(
#         "--attack_dir", 
#         required=True,
#         help="The relative path to the directory where image_attack.py *saved* the 1360 attacked images (e.g., 'data/SCID/attack_images')."
#     )
    
#     # --- 可选参数 ---
#     parser.add_argument(
#         "--target_dir", 
#         default="data/SCID",
#         help="The directory where the new train.txt, test.txt, and database.txt will be saved. [default: %(default)s]"
#     )
    
#     args = parser.parse_args()

#     # 1. 确保目标目录存在
#     target_dir_path = Path(args.target_dir)
#     target_dir_path.mkdir(parents=True, exist_ok=True)
    
#     # 2. 加载 gnd.json
#     print(f"Loading {args.gnd}...")
#     with open(args.gnd, 'r') as f:
#         gnd_data = json.load(f)
    
#     qimlist = gnd_data['qimlist'] # 40 个原始图的 "base names"
#     imlist = gnd_data['imlist']   # 1360 个攻击图的 "base names"
    
#     print(f"Loaded {len(qimlist)} query images and {len(imlist)} database images from gnd.json.")

#     # 3. 创建 "身份" 标签 (0 到 39)
#     # (例如 'image001' -> 0, 'image002' -> 1)
#     label_map = {base_name: i for i, base_name in enumerate(qimlist)}
    
#     original_lines = []
#     for base_name, label in label_map.items():
#         # 假设原始图像是 .jpg (如果不是，请修改这里的扩展名)
#         path = f"{args.originals_dir}/{base_name}.jpg"
#         original_lines.append(f"{path} {label}")
        
#     print(f"Built identity label map for {len(label_map)} original images.")

#     # 4. 写入 train.txt (用于训练)
#     train_txt_path = target_dir_path / "train.txt"
#     with open(train_txt_path, 'w') as f:
#         f.write("\n".join(original_lines))
#     print(f"Successfully created: {train_txt_path} (for training, {len(original_lines)} lines)")

#     # 5. 写入 test.txt (用于评估查询)
#     test_txt_path = target_dir_path / "test.txt"
#     with open(test_txt_path, 'w') as f:
#         f.write("\n".join(original_lines))
#     print(f"Successfully created: {test_txt_path} (for evaluation query, {len(original_lines)} lines)")

#     # 6. 写入 database.txt (用于评估数据库)
#     database_txt_path = target_dir_path / "database.txt"
#     db_lines_written = 0
#     with open(database_txt_path, 'w') as f:
#         for db_base_name in imlist:
#             found_label = None
#             # 找到这个攻击图像对应的原始 "身份" 标签
#             for q_base_name, label in label_map.items():
#                 if db_base_name.endswith(f"_{q_base_name}"):
#                     found_label = label
#                     break
            
#             if found_label is not None:
#                 # 假设 .jpg 扩展名
#                 db_path = f"{args.attack_dir}/{db_base_name}.jpg"
#                 f.write(f"{db_path} {found_label}\n")
#                 db_lines_written += 1
#             else:
#                 print(f"Warning: Could not find original query label for database image: {db_base_name}")
                
#     print(f"Successfully created: {database_txt_path} (for evaluation database, {db_lines_written} lines)")
    
#     if db_lines_written != len(imlist):
#         print(f"Warning: Wrote {db_lines_written} lines to database.txt, but gnd.json listed {len(imlist)} images.")
    
#     print("\nAll .txt files created successfully.")

# if __name__ == "__main__":
#     main()

import json
import os
import argparse
from pathlib import Path

def main():
    parser = argparse.ArgumentParser(description="Generate train.txt, test.txt, and database.txt from gnd.json.")
    
    # --- 必需的参数 ---
    parser.add_argument(
        "--gnd", 
        required=True, 
        help="Path to the 'gnd.json' file generated by image_attack.py."
    )
    
    parser.add_argument(
        "--originals_dir", 
        required=True,
        help="The relative path to the directory where your original query images are stored (e.g., 'jpg')."
    )

    parser.add_argument(
        "--attack_dir", 
        required=True,
        help="The relative path to the directory where image_attack.py saved the attacked images (e.g., 'attack_images')."
    )
    
    # --- 可选参数 ---
    parser.add_argument(
        "--target_dir", 
        default=".",
        help="The directory where the new train.txt, test.txt, and database.txt will be saved. [default: current directory]"
    )
    
    args = parser.parse_args()

    # 1. 确保目标目录存在
    target_dir_path = Path(args.target_dir)
    target_dir_path.mkdir(parents=True, exist_ok=True)
    
    # 2. 加载 gnd.json
    print(f"Loading {args.gnd}...")
    with open(args.gnd, 'r') as f:
        gnd_data = json.load(f)
    
    qimlist = gnd_data['qimlist'] # 原始图的 "base names"
    imlist = gnd_data['imlist']   # 攻击图的 "base names"
    
    print(f"Loaded {len(qimlist)} query images and {len(imlist)} database images from gnd.json.")

    # 3. 创建 "身份" 标签
    # (例如 'image001' -> 0, 'image002' -> 1)
    label_map = {base_name: i for i, base_name in enumerate(qimlist)}
    
    original_lines = []
    print("Checking original files to determine extensions (.png or .jpg)...")
    
    for base_name, label in label_map.items():
        # [修改点] 针对 MyScreenDataset：
        # 你的文件夹叫 'jpg'，但里面的原图可能是 .png。
        # 这里我们进行自动检测，而不是写死 .jpg
        
        # 构建完整的检查路径 (利用 pathlib)
        base_path_obj = Path(args.originals_dir) / base_name
        
        if base_path_obj.with_suffix('.png').exists():
            ext = ".png"
        elif base_path_obj.with_suffix('.jpg').exists():
            ext = ".jpg"
        elif base_path_obj.with_suffix('.jpeg').exists():
            ext = ".jpeg"
        else:
            # 如果找不到文件，默认给个 .png (根据你的截图，应该是png)
            # 并打印警告
            print(f"Warning: Could not find file for {base_name} in {args.originals_dir}, defaulting to .png")
            ext = ".png"

        # 生成写入 txt 的相对路径 (保留用户输入的路径风格，使用斜杠连接)
        # 结果类似: "jpg/image_123.png 0"
        path = f"{args.originals_dir}/{base_name}{ext}"
        original_lines.append(f"{path} {label}")
        
    print(f"Built identity label map for {len(label_map)} original images.")

    # 4. 写入 train.txt (用于训练)
    train_txt_path = target_dir_path / "train.txt"
    with open(train_txt_path, 'w') as f:
        f.write("\n".join(original_lines))
    print(f"Successfully created: {train_txt_path} (for training, {len(original_lines)} lines)")

    # 5. 写入 test.txt (用于评估查询)
    test_txt_path = target_dir_path / "test.txt"
    with open(test_txt_path, 'w') as f:
        f.write("\n".join(original_lines))
    print(f"Successfully created: {test_txt_path} (for evaluation query, {len(original_lines)} lines)")

    # 6. 写入 database.txt (用于评估数据库)
    database_txt_path = target_dir_path / "database.txt"
    db_lines_written = 0
    
    # 这里的 suffix 保持 .jpg 是对的，因为 image_attack.py 生成的攻击图都是 jpg
    with open(database_txt_path, 'w') as f:
        for db_base_name in imlist:
            found_label = None
            # 找到这个攻击图像对应的原始 "身份" 标签
            for q_base_name, label in label_map.items():
                # 匹配逻辑：攻击图文件名通常以 _原图文件名 结尾
                # 例如 blur_3_image_001 对应 image_001
                if db_base_name.endswith(f"_{q_base_name}"):
                    found_label = label
                    break
            
            if found_label is not None:
                # 攻击图我们确定是 .jpg (由 image_attack.py 生成)
                db_path = f"{args.attack_dir}/{db_base_name}.jpg"
                f.write(f"{db_path} {found_label}\n")
                db_lines_written += 1
            else:
                print(f"Warning: Could not find original query label for database image: {db_base_name}")
                
    print(f"Successfully created: {database_txt_path} (for evaluation database, {db_lines_written} lines)")
    
    if db_lines_written != len(imlist):
        print(f"Warning: Wrote {db_lines_written} lines to database.txt, but gnd.json listed {len(imlist)} images.")
    
    print("\nAll .txt files created successfully.")

if __name__ == "__main__":
    main()